### PR TITLE
Futurenet 20.0.0 release

### PR DESCRIPTION
**Pull request by chowbao**
Updates for futurenet release of 20.0.0

Changed DAGs to run less frequently (run every 2 hours)

Note: merge when testnet is reset and upgraded (and update airflow task start dates)

### CODE REVIEW

**Comment by chowbao** [comment]
Note: Cancelled deploy-to-dev as this is supposed to run in futurenet and not testnet

**Review by sydneynotthecity — COMMENTED** [review]
I think there should also be schema changes for `history_effects`, `history_transactions` and `history_operations` based on the `stellar-etl` changes in its corresponding [PR](https://github.com/stellar/stellar-etl/pull/209/files).  Might want to double check to confirm

**Review by sydneynotthecity — APPROVED** [review]
LGTM

**Review by sydneynotthecity — APPROVED** [review]
Re-reviewed, still looks good

**Pull request merged**
